# Generated by Django 2.1.4 on 2018-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='confirmed_date',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='created',
        ),
        migrations.AddField(
            model_name='appuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, default='abc@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
