# Generated by Django 2.1.4 on 2018-12-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181227_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='confirmed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
