# Generated by Django 2.1.4 on 2018-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_review_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='spec_description',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
