# Generated by Django 2.1.4 on 2018-12-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_specialty_spec_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'specialties'},
        ),
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
