# Generated by Django 2.1.4 on 2018-12-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181228_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='finder',
            field=models.BooleanField(default=True),
        ),
    ]
