# Generated by Django 2.1.4 on 2018-12-28 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appuser_finder'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='givers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
