# Generated by Django 2.1.4 on 2018-12-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_specialty_givers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
