# Generated by Django 2.1.4 on 2018-12-28 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='from_whom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
