# Generated by Django 2.1.4 on 2018-12-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181228_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['last_name']},
        ),
    ]
