# Generated by Django 2.1.4 on 2019-01-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181228_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', max_length=510, unique=True),
        ),
    ]
