# Generated by Django 2.1.4 on 2019-01-05 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190102_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
