# Generated by Django 2.1.4 on 2019-01-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190105_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
